class HardConfig:
    MAX_ENERGY = 120
    MAX_ATTENTION = 120
    MAX_FATIGUE = 100
    MEMORY_SLOTS = 30

    ACTION_COSTS = {
        'generate': (7, 5, 0, 3),
        'explore':  (22, 16, 1, 6),
        'refine':   (5, 8, 0, 3),
        'recall':   (2, 2, 0, 1),
        'combine':  (14, 11, 1, 5),
        'rest':     (-7, -9, 0, -7),
        'forget':   (4, 2, -1, 2),
    }

    COMMITMENT_WINDOW = 5
    COMMITMENT_VIOLATION_PENALTY = {'energy': -20, 'attention': -30, 'fatigue': +15}
    COMMITMENT_THRESHOLD_CONFIDENCE = 0.65

    FAILURE_BURDEN_MAX = 100
    COST_MULTIPLIER_MAX = 1.8

    EMERGENCY_BURDEN_THRESHOLD = 75
    EMERGENCY_ENERGY_THRESHOLD = 20
    COMA_BURDEN = 100
    COMA_ENERGY = 12
    COMA_DURATION = 5

    TRAUMA_BLOCK_THRESHOLD = 0.75
    TRAUMA_BLOCK_DURATION = 12

    WORLD_MODEL_UPDATE_RATE = 0.03
    WORLD_MODEL_HIDDEN_DIM = 16
    VECTOR_DIM = 36

    NN_INPUT_DIM = 36
    NN_HIDDEN_1 = 48
    NN_HIDDEN_2 = 64
    NN_HIDDEN_3 = 32
    NN_OUTPUT_DIM = 6

    NN_LEARNING_RATE = 0.008
    NN_TRAINING_EPOCHS = 10
    NN_BATCH_SIZE = 32
    NN_TRAIN_INTERVAL = 20
    NN_SAMPLE_THRESHOLD_INITIAL = 0.15
    NN_SAMPLE_THRESHOLD_MAX = 0.7
    NN_CONFIDENCE_LOSS_THRESH = 0.04
    NN_FORCED_SHAPE_PROB = 0.85
    NN_POST_TRAIN_FORCED_SHAPE_PROB = 0.65
    NN_GENERATE_BONUS_TRAINED = 0.8
    NN_SHAPE_UTILITY_BONUS = 0.8

    BOOTSTRAPPING_CYCLES = 35
    BOOTSTRAP_ENERGY_REWARD = 10
    BOOTSTRAP_BURDEN_REDUCTION = -12
    BOOTSTRAP_COST = (2, 1, 1)

    FORESIGHT_STEPS = 1
    PLANNING_DISCOUNT = 0.9

    EXPLORATION_NOISE_STD = 0.1
    CURIOSITY_BONUS = 0.4

    REPETITION_PENALTY_PER_USE = 0.05
    STATE_TRANSITION_NOISE = 0.08

    ACTION_SHIFT = {
        'explore': 0.25, 'refine': 0.08, 'generate': 0.02,
        'combine': 0.12, 'rest': -0.07, 'recall': 0.0, 'forget': 0.0
    }

    REST_COOLDOWN = 5
    REST_FATIGUE_REDUCTION = 10
    REST_ENERGY_GAIN_BASE = 8
    REST_ATTENTION_GAIN_BASE = 12
    BURDEN_RECOVERY_REST = -8

    STIMULUS_WEIGHT = 0.25
    STIMULUS_SIMILARITY_THRESHOLD = 0.1
    PATTERNS = ['wave', 'fractal', 'cellular', 'lsystem', 'shape']

    REPETITION_STAGNATION_THRESHOLD = 5
    REWARD_STAGNATION_WINDOW = 8
    REWARD_IMPROVEMENT_THRESHOLD = 0.03
    PERSISTENCE_BONUS_CYCLES = 5

    REWARD_CONTOUR_SIM_WEIGHT = 0.4
    REWARD_RADIAL_SIM_WEIGHT = 0.3
    REWARD_AREA_COHERENCE_WEIGHT = 0.2
    REWARD_NOVELTY_WEIGHT = 0.1
    REWARD_SURVIVAL_WEIGHT = 0.0
